// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBbJIKbGX2_FzF6Ol75OeLTnQdfZpoOwg',
    appId: '1:233637833699:web:047b1451c8c894b465ced6',
    messagingSenderId: '233637833699',
    projectId: 'chatapptute-ec7cf',
    authDomain: 'chatapptute-ec7cf.firebaseapp.com',
    storageBucket: 'chatapptute-ec7cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk_1qwpapTZXVRe7rPyVX_r_Lb_DIpVnE',
    appId: '1:233637833699:android:1f6992d58f754cda65ced6',
    messagingSenderId: '233637833699',
    projectId: 'chatapptute-ec7cf',
    storageBucket: 'chatapptute-ec7cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf3VCvPxVyIfTfmpY24uHKhg5pqM6y8nY',
    appId: '1:233637833699:ios:a55d2d3981b5abbb65ced6',
    messagingSenderId: '233637833699',
    projectId: 'chatapptute-ec7cf',
    storageBucket: 'chatapptute-ec7cf.appspot.com',
    iosBundleId: 'com.example.chatMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf3VCvPxVyIfTfmpY24uHKhg5pqM6y8nY',
    appId: '1:233637833699:ios:36fb45972cbd606b65ced6',
    messagingSenderId: '233637833699',
    projectId: 'chatapptute-ec7cf',
    storageBucket: 'chatapptute-ec7cf.appspot.com',
    iosBundleId: 'com.example.chatMessenger.RunnerTests',
  );
}
